"""empty message

Revision ID: 01d1bf9fd4cf
Revises: 03a6f8c2908e
Create Date: 2025-06-22 21:55:36.969114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d1bf9fd4cf'
down_revision = '03a6f8c2908e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_talent', sa.Boolean(), nullable=True))
        batch_op.drop_column('looking_for_talent')
    
    op.execute('UPDATE "Venue" SET seeking_talent = False WHERE seeking_talent IS NULL;')
    op.alter_column('Venue', 'seeking_talent', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('seeking_talent')

    # ### end Alembic commands ###
