"""empty message

Revision ID: 03a6f8c2908e
Revises: c375c7a2550f
Create Date: 2025-06-20 17:06:50.496048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a6f8c2908e'
down_revision = 'c375c7a2550f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('looking_for_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    
    op.execute('UPDATE "Venue" SET looking_for_talent = False WHERE looking_for_talent IS NULL;')
    op.alter_column('Venue', 'looking_for_talent', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('looking_for_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
