"""empty message

Revision ID: 246e6a5a5182
Revises: 01d1bf9fd4cf
Create Date: 2025-06-22 22:05:55.319816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246e6a5a5182'
down_revision = '01d1bf9fd4cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_description', sa.String(length=500), nullable=True))
        batch_op.drop_column('seeking')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('seeking_description')

    # ### end Alembic commands ###
