"""empty message

Revision ID: f145b0d331e3
Revises: e84b9bd3e641
Create Date: 2025-06-20 15:06:15.908686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f145b0d331e3'
down_revision = 'e84b9bd3e641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Genres', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['genre'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Genres', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
